### ISSUE TITLE
HTTP Request Node times out in Dify's workflow

### ISSUE THREAD

**Issue by gijigae** [nikawang/dify-azure-terraform#1]
Thank you so much for creating the terraform implementation! There is one issue I want to share. Everything works intended except the HTTP Request node in Chat/Workflow. Irrespective of any URL, the HTTP Request node always times out. I suspect it might be something to do with network settings, but not sure how to fix the problem. Please have a look when you have time.

### Dify deployed on VM
<img width="1881" alt="image" src="https://github.com/nikawang/dify-azure-terraform/assets/81459/e37496ef-4db6-439f-8b8d-67b00e5f4da3">

### Dify deployed on Azure Container Apps with Terraform
<img width="1881" alt="image" src="https://github.com/nikawang/dify-azure-terraform/assets/81459/fa8cce72-a382-4dc1-9423-dba9c76ad104">

**Comment by gijigae** [comment]
Confirmed the issue can be resolved by removing SSRF Proxy settings from the api container. See the details in the link below. 

https://github.com/langgenius/dify/issues/6244#issuecomment-2225637707

**Comment by nikawang** [comment]
Close the issue, as it's been addressed on https://github.com/langgenius/dify/issues/6244. Thanks!
